repository_type: pipeline
lint:
  actions_ci: False
  files_exist:
    - conf/modules.config
  files_unchanged:
    - .gitattributes
    - .gitignore
    - assets/multiqc_config.yml
    - assets/nf-core-sarek_logo_light.png
    - docs/images/nf-core-sarek_logo_dark.png
    - docs/images/nf-core-sarek_logo_light.png
    - lib/NfcoreSchema.groovy
    - lib/NfcoreTemplate.groovy
  schema_params: False
  template_strings: False
