name: nf-core CI
# This workflow runs the pipeline with the minimal test dataset to check that it completes without any syntax errors
on:
  push:
    branches: [dev]
  pull_request:
  release:
    types: [published]

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run pipeline with test data
    # Only run on push if this is the nf-core dev branch (merged PRs)
    if: "${{ github.event_name != 'push' || (github.event_name == 'push' && github.repository == 'nf-core/sarek') }}"
    runs-on: ubuntu-latest
    strategy:
      # HACK Remove after DSL2 rewrite is done
      fail-fast: false
      matrix:
        NXF_VER:
          - "21.10.3"
          - "latest-everything"
        test:
          - "default"
        profile: ["docker", "singularity", "conda"]
        exclude:
          - NXF_VER: "latest-everything"
            profile: "conda"
    env:
      NXF_ANSI_LOG: false
    steps:
      - name: Check out pipeline code
        uses: actions/checkout@v3

      - uses: actions/cache@v2
        with:
          path: /usr/local/bin/nextflow
          key: ${{ runner.os }}
          restore-keys: |
            ${{ runner.os }}-nextflow-

      - name: Install Nextflow ${{ matrix.NXF_VER }}
        uses: nf-core/setup-nextflow@v1
        with:
          version: "${{ matrix.NXF_VER }}"

      - name: Install nf-test
        run: |
          wget -qO- https://code.askimed.com/install/nf-test | bash
          sudo mv nf-test /usr/local/bin/

      - name: Set up Singularity
        if: matrix.profile == 'singularity'
        uses: eWaterCycle/setup-singularity@v5
        with:
          singularity-version: 3.7.1

      - name: Set up miniconda
        if: matrix.profile == 'conda'
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge,bioconda,defaults
          python-version: ${{ matrix.python-version }}

      - name: Conda clean
        if: matrix.profile == 'conda'
        run: conda clean -a

      - name: Run nf-test
        uses: Wandalen/wretry.action@v1.0.11
        with:
          command: PROFILE=${{ matrix.profile }} nf-test test tests/${{ matrix.test }}/*.nf.test --tap=test.tap
          attempt_limit: 3

      - name: Output log on failure
        if: failure()
        run: |
          sudo apt install bat > /dev/null
          batcat --decorations=always --color=always test.tap
          batcat --decorations=always --color=always /home/runner/.nf-test/tests/*/meta/std.{err.out}
          batcat --decorations=always --color=always /home/runner/.nf-test/tests/*/meta/nextflow.log
          batcat --decorations=always --color=always /home/runner/.nf-test/tests/*/meta/trace.csv
          batcat --decorations=always --color=always /home/runner/.nf-test/tests/*/meta/params.json


